name: base
img_size: ${dataset.img_size} # resolution (H=W)
patch_size: 16                  # 16x16 patchees
img_chls: ${dataset.img_chls}
n_class: ${dataset.n_class}
n_layer: 12
n_heads: 12
n_embd: 768
mlp_dim: 3072
drop_rate: 0.1
attn_drop_rate: 0.1