name: "Swin-T-TinyImageNet"
img_size: ${dataset.img_size}
patch_size: 2
patch_norm: true
img_chls: ${dataset.img_chls}
n_class: ${dataset.n_class}
n_embed: 96
depths: [2, 2, 6, 2]
n_heads: [3, 6, 12, 24]
window_size: 8
mlp_ratio: 4.
drop_rate: 0.
attn_drop_rate: 0.
stoch_depth_drop_rate: .1