name: "Swin-B"
img_size: ${dataset.img_size}
patch_size: 4
patch_norm: true
img_chls: ${dataset.img_chls}
n_class: ${dataset.n_class}
n_embed: 128
depths: [2, 2, 18, 2]
n_heads: [4, 8, 16, 32]
window_size: 7
mlp_ratio: 4.
drop_rate: 0.
attn_drop_rate: 0.
stoch_depth_drop_rate: 0.