name: tiny
img_size: ${dataset.img_size} # resolution (H=W)
patch_size: 8                 # 8x8 patch size
img_chls: ${dataset.img_chls}
n_class: ${dataset.n_class}
n_layer: 12
n_heads: 3
n_embd: 192
mlp_dim: 768
drop_rate: 0.1
attn_drop_rate: 0.1